'use client';
import Image from 'next/image';
import {useEffect,useRef,useState} from 'react';
import {Download,ImagePlus,Loader2,Trash2,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
type SavedImage={id:string;prompt:string;provider:string;mime_type:string;created_at:string;project_id:string|null};
export function ImageStudio({providers,projects}:{projects:{id:string;name:string}[];providers:{id:string;name:string;notice:string}[]}){
 const [assetId,setAssetId]=useState<string>();const [saving,setSaving]=useState(false);
 const [provider,setProvider]=useState(providers[0]?.id??'');const [prompt,setPrompt]=useState('');const [src,setSrc]=useState('');const [caption,setCaption]=useState('');const [mime,setMime]=useState('image/png');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [images,setImages]=useState<SavedImage[]>([]);const [note,setNote]=useState('');const [confirm,setConfirm]=useState<string>();const [deleting,setDeleting]=useState<string>();const pending=useRef(false);const controller=useRef<AbortController|null>(null);
 async function history(){const r=await fetch('/api/images');const data=await r.json();if(r.ok)setImages(data.images);else setNote('Image history could not be loaded.');}
 useEffect(()=>{let live=true;fetch('/api/images').then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{if(live)setImages(d.images);}).catch(()=>{if(live)setNote('Image history could not be loaded.');});return()=>{live=false;controller.current?.abort();};},[]);
 async function generate(){if(pending.current||!prompt.trim()||!provider)return;pending.current=true;setBusy(true);setError('');setNote('');const abort=new AbortController();controller.current=abort;try{const r=await fetch('/api/images',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,provider}),signal:abort.signal});const data=await r.json();if(!r.ok)throw Error(data.error?.message||'Image generation failed.');setAssetId(data.id);setSrc(data.src);setMime(data.mime);setCaption(prompt);setNote(data.warning||'Saved.');if(data.provider&&data.provider!==provider){setProvider(data.provider);setNote('Switched to an available image model. '+(data.warning||'Saved.'));}await history().catch(()=>setNote('Image ready. History could not refresh.'));}catch(e){if(abort.signal.aborted)setNote('Stopped waiting. If the provider already finished, the image may appear in Recent Images.');else setError(e instanceof Error?e.message:'Please retry.');}finally{pending.current=false;setBusy(false);controller.current=null;}}
 async function remove(id:string){if(deleting)return;setDeleting(id);setError('');try{const r=await fetch('/api/images/'+id,{method:'DELETE'});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not remove image.');setImages(rows=>rows.filter(i=>i.id!==id));setConfirm(undefined);if(src==='/api/images/'+id)setSrc('');setNote('Removed from Recent Images. Saved asset copies are preserved.');}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{setDeleting(undefined);}}
 async function save(projectId:string){if(!assetId||saving)return;setSaving(true);setError('');try{const r=await fetch('/api/images/'+assetId,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId})});const d=await r.json();if(!r.ok)throw Error(d.error);setNote('Saved to project assets.');}catch(e){setError(e instanceof Error?e.message:'Could not save image.');}finally{setSaving(false);}}
 return <div className="scrollbar-thin flex-1 overflow-y-auto"><div className="mx-auto max-w-4xl px-5 py-6 sm:px-8"><h1 className="text-lg font-medium">Images</h1>
 {!providers.length?<p className="mt-6 text-sm text-muted-foreground">Image generation is unavailable. Your saved images remain below.</p>:<section className="mt-5 rounded-2xl border bg-surface/40 p-3"><label htmlFor="image-prompt" className="sr-only">Describe your image</label><Textarea id="image-prompt" rows={3} maxLength={4000} value={prompt} onChange={e=>setPrompt(e.target.value)} disabled={busy} placeholder="Describe an image…" className="border-0 bg-transparent shadow-none"/><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><select aria-label="Image model" className="min-w-0 max-w-full rounded-md bg-transparent px-2 py-2 text-xs" value={provider} disabled={busy} onChange={e=>setProvider(e.target.value)}>{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="flex gap-2">{busy&&<Button variant="ghost" onClick={()=>controller.current?.abort()}><X className="size-4"/>Cancel</Button>}<Button disabled={busy||!prompt.trim()} onClick={()=>void generate()}>{busy?<Loader2 className="size-4 animate-spin"/>:<ImagePlus className="size-4"/>}{busy?'Generating…':error?'Retry':'Generate'}</Button></div></div></section>}
 {error&&<p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}<p role="status" className="mt-3 text-xs text-muted-foreground">{note}</p>
 {src&&<section className="mt-5" aria-label="Generated image"><Image unoptimized width={768} height={768} src={src} alt={caption} className="max-h-[65vh] w-full rounded-xl object-contain"/><a className="platform-button mt-3" href={src} download={'unbound-image.'+(mime==='image/jpeg'?'jpg':mime.split('/')[1])}><Download className="size-4"/>Download</a>{assetId&&projects.length>0&&<select aria-label="Save image to project" className="platform-input ml-3 mt-3 max-w-full" value="" disabled={saving} onChange={e=>{if(e.target.value)void save(e.target.value);}}><option value="">Save to project…</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}</section>}
 <h2 className="mt-8 text-sm font-medium">Recent Images</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{images.map(img=><article key={img.id} className="group relative min-w-0"><button className="block w-full rounded-xl text-left focus-visible:ring-2" onClick={()=>{setAssetId(img.id);setSrc('/api/images/'+img.id);setCaption(img.prompt);setMime(img.mime_type);setPrompt(img.prompt);}}><Image unoptimized loading="lazy" width={256} height={256} src={'/api/images/'+img.id} alt={img.prompt} className="aspect-square w-full rounded-xl object-cover"/><p className="mt-2 line-clamp-1 text-xs text-muted-foreground">{img.prompt}</p></button><button aria-label="Remove image from recents" title="Remove image from recents" onClick={()=>setConfirm(img.id)} className="absolute right-2 top-2 flex size-8 items-center justify-center rounded-full border bg-background/90 focus-visible:opacity-100 focus-visible:ring-2 sm:opacity-0 group-hover:opacity-100 [@media(hover:none)]:opacity-100"><Trash2 size={14}/></button>{confirm===img.id&&<div role="group" aria-label="Confirm image removal" className="absolute inset-x-0 bottom-0 rounded-xl border bg-background p-3 text-xs shadow-lg"><p>Remove from recents? {img.project_id?'This image belongs to a project. ':''}Saved assets are kept so websites stay intact.</p><div className="mt-3 flex gap-3"><button disabled={!!deleting} className="underline" onClick={()=>void remove(img.id)}>{deleting===img.id?'Removing…':'Remove'}</button><button disabled={!!deleting} onClick={()=>setConfirm(undefined)}>Keep</button></div></div>}</article>)}</div>{!images.length&&<p className="mt-5 text-sm text-muted-foreground">No recent images.</p>}
 </div></div>;
}
