'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Loader2,Video,Download,Trash2} from 'lucide-react';
import type {VideoJob} from '@/lib/videos/types';
export function VideoStudio({available,projects,initial}:{initial:VideoJob[];available:boolean;projects:{id:string;name:string}[]}){
 const [prompt,setPrompt]=useState('');const [ratio,setRatio]=useState('16:9');const [jobs,setJobs]=useState<VideoJob[]>(initial);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [confirm,setConfirm]=useState<string>();const [selected,setSelected]=useState<string>();const pending=useRef(false);
 const refresh=useCallback(async()=>{try{const r=await fetch('/api/videos');const d=await r.json();if(!r.ok)throw Error(d.error);setJobs(d.videos);}catch{setError('Video history could not load. Refresh to retry.');}},[]);
 const active=jobs.some(j=>['queued','running'].includes(j.status));
 useEffect(()=>{if(!active)return;const timer=setInterval(()=>void refresh(),10000);return()=>clearInterval(timer);},[refresh,active]);
 async function generate(){if(pending.current||active||!prompt.trim())return;pending.current=true;setBusy(true);setError('');try{const r=await fetch('/api/videos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,aspectRatio:ratio})});const d=await r.json();if(!r.ok)throw Error(d.error);setJobs(v=>[d.job,...v]);setSelected(d.job.id);setNotice('Generation is saved. You can leave and return to this page.');}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{pending.current=false;setBusy(false);}}
 async function update(id:string,action:string,projectId?:string){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const r=await fetch('/api/videos/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,projectId})});const d=await r.json();if(!r.ok)throw Error(d.error);setConfirm(undefined);setNotice(action==='save'?'Saved to project assets.':action==='cancel'?'Stopped. The provider may still finish its remote job.':'Removed from recents. Saved video assets are preserved.');await refresh();}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{pending.current=false;setBusy(false);}}
 const current=jobs.find(j=>j.id===selected)??jobs[0];
 return <div className="flex-1 overflow-y-auto"><div className="mx-auto max-w-4xl px-5 py-6 sm:px-8"><h1 className="text-lg font-medium">Videos</h1>{!available?<p className="mt-6 text-sm text-muted-foreground">Video creation is unavailable. Your saved videos remain below.</p>:<section className="mt-5 rounded-2xl border bg-surface/40 p-3"><textarea className="w-full resize-y bg-transparent p-2 text-sm outline-none focus-visible:ring-2" rows={3} aria-label="Describe your video" placeholder="Describe a short video…" value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={4000}/><div className="mt-2 flex flex-wrap items-center gap-3"><select className="bg-transparent text-xs" aria-label="Video aspect ratio" value={ratio} onChange={e=>setRatio(e.target.value)}><option value="16:9">Landscape 16:9</option><option value="9:16">Portrait 9:16</option></select><span className="text-xs text-muted-foreground">~5 seconds · 480p</span><button className="platform-button ml-auto" disabled={busy||active||!prompt.trim()} onClick={()=>void generate()}>{busy||active?<Loader2 size={14} className="animate-spin"/>:<Video size={14}/>}Generate</button></div><p className="mt-3 px-2 text-xs text-muted-foreground">Uses the connected Hugging Face free allowance. Availability is limited.</p></section>}
 {error&&<p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}<p role="status" className="mt-3 text-xs text-muted-foreground">{notice}</p>
 {current&&<section className="mt-5">{current.status==='complete'?<><video key={current.id} controls playsInline preload="metadata" className="max-h-[65vh] w-full rounded-xl bg-black" src={'/api/videos/'+current.id} aria-label={current.prompt}/><div className="mt-3 flex flex-wrap gap-3"><a className="platform-button" href={'/api/videos/'+current.id+'?download=1'}><Download size={14}/>Download</a>{projects.length>0&&<select aria-label="Save video to project" value="" disabled={busy} className="platform-input" onChange={e=>{if(e.target.value)void update(current.id,'save',e.target.value);}}><option value="">Save to project…</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}</div></>:['queued','running'].includes(current.status)?<div className="flex items-center gap-3 border-b py-8 text-sm"><Loader2 className="size-4 animate-spin"/>{current.status==='queued'?'Queued':'Creating your video…'}<button className="platform-button ml-auto" disabled={busy} onClick={()=>void update(current.id,'cancel')}>Cancel</button></div>:<div className="border-b py-6 text-sm"><p>{current.error??'Generation stopped.'}</p>{available&&<button className="platform-button mt-3" disabled={busy||active} onClick={()=>{setPrompt(current.prompt);setRatio(current.aspect_ratio);setNotice('Prompt restored. Choose Generate to retry.');}}>Retry prompt</button>}</div>}</section>}
 <h2 className="mt-8 text-sm font-medium">Recent Videos</h2><ul className="mt-3 divide-y">{jobs.map(job=><li key={job.id} className="group py-3"><div className="flex items-center gap-3"><button className="min-w-0 flex-1 truncate text-left text-sm focus-visible:ring-2" onClick={()=>{setSelected(job.id);setPrompt(job.prompt);}}>{job.prompt}</button><span className="text-xs text-muted-foreground">{job.status}</span><button aria-label="Remove video from recents" title="Remove video from recents" disabled={busy} className="rounded p-2 focus-visible:ring-2 sm:opacity-0 group-hover:opacity-100 focus-visible:opacity-100 [@media(hover:none)]:opacity-100" onClick={()=>setConfirm(job.id)}><Trash2 size={14}/></button></div>{confirm===job.id&&<div className="mt-2 flex flex-wrap items-center gap-3 text-xs"><span>Remove from recents? Saved project assets will be kept.</span><button className="underline" disabled={busy} onClick={()=>void update(job.id,'hide')}>Remove</button><button disabled={busy} onClick={()=>setConfirm(undefined)}>Keep</button></div>}</li>)}</ul>{!jobs.length&&<p className="mt-4 text-sm text-muted-foreground">No videos yet.</p>}</div></div>;
}
