'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Markdown} from '@/components/markdown';
import type {Integration} from '@/lib/integrations/catalog';
import type {ToolResult} from '@/lib/integrations/research';
export function ToolWorkspace({initial}:{initial:(Integration&{status:string;checkedAt:string|null})[]}){
 const [id,setId]=useState('crossref');const [input,setInput]=useState('');const [result,setResult]=useState<ToolResult>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const spec=initial.find(p=>p.id===id)!;
 async function run(){setBusy(true);setError('');try{const r=await fetch('/api/integrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,input}),signal:AbortSignal.timeout(50000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed.');setResult(d);}catch(e){setError(e instanceof Error?e.message:'Request failed.');}finally{setBusy(false);}}
 return <div className="overflow-auto p-5 sm:p-9"><div className="mx-auto max-w-5xl"><p className="text-xs uppercase tracking-[.25em] text-subtle">Connected knowledge</p><h1 className="mt-2 text-3xl">Tools</h1><p className="mt-3 text-sm text-muted-foreground">Search research, read webpages, and create embeddings. Data sources are separate from chat models.</p><div className="mt-7 grid gap-5 md:grid-cols-[.8fr_1.2fr]"><section className="platform-card space-y-4"><label className="block text-sm">Integration<select className="platform-input mt-2 w-full" value={id} onChange={e=>{setId(e.target.value);setResult(undefined);setError('');}} disabled={busy}>{initial.filter(p=>['research','reader','embeddings'].includes(p.kind)).map(p=><option key={p.id} value={p.id}>{p.name}{p.status==='CONFIGURATION REQUIRED'?' · needs key':''}</option>)}</select></label><p className="text-xs text-muted-foreground">{spec.allowance}</p><a className="text-xs underline" href={spec.docs} target="_blank" rel="noreferrer">Official API information</a>{spec.status==='CONFIGURATION REQUIRED'&&<p className="text-xs">The owner needs to configure {spec.env} and {spec.id.toUpperCase()}_FREE_TIER_CONFIRMED.</p>}<label className="block text-sm">{spec.kind==='reader'?'Webpage URL':spec.kind==='embeddings'?'Text, one item per line':'Search query'}<textarea className="platform-input mt-2 w-full" rows={5} value={input} onChange={e=>setInput(e.target.value)} maxLength={4000}/></label><button className="platform-button" disabled={busy||!input.trim()||spec.status==='CONFIGURATION REQUIRED'} onClick={()=>void run()}>{busy?'Working…':'Run tool'}</button>{error&&<p className="text-sm text-destructive" role="alert">{error}</p>}<p className="text-xs text-subtle">{spec.checkedAt?'A request has been observed by this server.':'Configured access is not a guarantee of availability. Each request is checked live.'}</p></section><section className="platform-card min-w-0" aria-live="polite">{result?<><Markdown content={result.content}/>{result.vectors&&<a className="platform-button mt-4" download="embeddings.json" href={'data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(result.vectors))}>Download vectors</a>}</>:<p className="text-sm text-subtle">Results and source links appear here.</p>}</section></div><p className="mt-6 text-sm text-muted-foreground">Chat integrations are available through the chat model selector. <Link href="/image-gen" className="underline">Open image studio</Link>.</p></div></div>;
}
