export type ToolKind='chat'|'research'|'reader'|'embeddings'|'image'|'transcription'|'ocr';
export interface Integration {id:string;name:string;kind:ToolKind;model:string;env?:string;optionalKey?:boolean;allowance:string;docs:string;notice?:string;}
/** Official sources reviewed 2026-09-29. Data APIs are not described as AI models. */
export const INTEGRATIONS:readonly Integration[]=[
 {id:'sambanova',name:'SambaNova',kind:'chat',model:'DeepSeek-V3.1 · Llama 3.3 70B · GPT OSS 120B',env:'SAMBANOVA_API_KEY',allowance:'No-card Free tier: 20 RPM, 20 requests/day and 200k tokens/day per listed model.',docs:'https://docs.sambanova.ai/docs/en/models/rate-limits'},
 {id:'cohere',name:'Cohere',kind:'chat',model:'north-mini-code-1-0',env:'COHERE_API_KEY',allowance:'North Mini Code: free within key rate limits. Trial key: 1,000 calls/month. Confirm permitted production use before enabling.',docs:'https://docs.cohere.com/docs/north-mini-code-1.0'},
 {id:'tavily',name:'Tavily',kind:'research',model:'Basic Search',env:'TAVILY_API_KEY',allowance:'1,000 credits/month; basic search uses one credit. Keep pay-as-you-go disabled.',docs:'https://docs.tavily.com/documentation/api-credits'},
 {id:'exa',name:'Exa',kind:'research',model:'Search',env:'EXA_API_KEY',allowance:'$10 recurring monthly credit plus $10 signup bonus; no payment method required.',docs:'https://exa.ai/pricing'},
 {id:'brave',name:'Brave Search',kind:'research',model:'Web Search',env:'BRAVE_API_KEY',allowance:'$5 monthly credit. Use prepaid with auto-reload off; card required. Results are not saved by Unbound.',docs:'https://api-dashboard.search.brave.com/documentation/resources/help-feedback'},
 {id:'serper',name:'Serper',kind:'research',model:'Google Search',env:'SERPER_API_KEY',allowance:'2,500 signup queries; no card required. One-time allowance.',docs:'https://serper.dev/'},
 {id:'serpapi',name:'SerpAPI',kind:'research',model:'Google Search',env:'SERPAPI_API_KEY',allowance:'250 searches/month; 50/hour on Free.',docs:'https://serpapi.com/pricing'},
 {id:'searchapi',name:'SearchAPI',kind:'research',model:'Google Search',env:'SEARCHAPI_API_KEY',allowance:'100 signup requests; no card required. One-time allowance.',docs:'https://www.searchapi.io/'},
 {id:'firecrawl',name:'Firecrawl',kind:'research',model:'Web Search',env:'FIRECRAWL_API_KEY',allowance:'1,000 free credits/month; search consumes credits by returned results. No card required.',docs:'https://www.firecrawl.dev/pricing'},
 {id:'jina',name:'Jina AI',kind:'reader',model:'Reader',env:'JINA_API_KEY',optionalKey:true,allowance:'Reader without a key: 20 RPM. Optional free-key allowance is account-specific; auto top-up must stay off.',docs:'https://jina.ai/reader/'},
 {id:'voyage',name:'Voyage AI',kind:'embeddings',model:'voyage-4-lite',env:'VOYAGE_API_KEY',allowance:'First 200 million tokens for voyage-4-lite; no recurring reset. Keep billing disabled.',docs:'https://docs.voyageai.com/docs/pricing'},
 {id:'aihorde',name:'AI Horde',kind:'image',model:'Community image workers',env:'AI_HORDE_API_KEY',optionalKey:true,allowance:'Free volunteer queue. Anonymous access has lowest priority; no guaranteed completion time.',docs:'https://github.com/Haidra-Org/AI-Horde',notice:'Anonymous prompts and images are shared publicly and may contribute to research datasets. Use non-private prompts.'},
 {id:'deepgram',name:'Deepgram',kind:'transcription',model:'nova-3',env:'DEEPGRAM_API_KEY',allowance:'$200 signup credit; no expiration or credit card required. One-time allowance.',docs:'https://deepgram.com/pricing'},
 {id:'assemblyai',name:'AssemblyAI',kind:'transcription',model:'Universal transcription',env:'ASSEMBLYAI_API_KEY',allowance:'Free signup tier: up to 185 prerecorded hours, depending on model; no card required.',docs:'https://www.assemblyai.com/pricing'},
 {id:'ocrspace',name:'OCR.space',kind:'ocr',model:'OCR Engine 2',env:'OCRSPACE_API_KEY',allowance:'25,000 requests/month; 1 MB/file, 3 PDF pages.',docs:'https://ocr.space/ocrapi'},
 {id:'openalex',name:'OpenAlex',kind:'research',model:'Scholarly works (data API)',env:'OPENALEX_API_KEY',optionalKey:true,allowance:'Anonymous $0.10/day API budget; free account key $1/day, no payment method required.',docs:'https://help.openalex.org/api/authentication/'},
 {id:'semantic',name:'Semantic Scholar',kind:'research',model:'Academic Graph',env:'SEMANTIC_SCHOLAR_API_KEY',optionalKey:true,allowance:'Free shared public access; optional key initially 1 request/second.',docs:'https://webflow.semanticscholar.org/product/api'},
 {id:'crossref',name:'Crossref',kind:'research',model:'DOI metadata (data API)',allowance:'Free public metadata API; respect the service rate limits.',docs:'https://www.crossref.org/documentation/retrieve-metadata/rest-api/'},
 {id:'arxiv',name:'arXiv',kind:'research',model:'Research preprints (data API)',allowance:'Free public API; requests spaced at least 3 seconds apart, shared results cached.',docs:'https://info.arxiv.org/help/api/user-manual.html'},
 {id:'wikimedia',name:'Wikimedia',kind:'research',model:'Wikipedia Search (data API)',allowance:'Free public API with fair-use rate limits; source attribution retained.',docs:'https://www.mediawiki.org/wiki/API:Search'},
];
