'use client';
import {useRouter} from 'next/navigation';
import {useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {getSiteOrigin} from '@/lib/auth/site-url';
import type {HandleRow} from '@/lib/projects/types';
export function IdentityForm({initial,userId,anonymous}:{initial:HandleRow|null;userId:string;anonymous:boolean}){
 const router=useRouter();
 const [username,setUsername]=useState(initial?.username??'');const [name,setName]=useState(initial?.display_name??'');const [exists,setExists]=useState(!!initial);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);
 async function save(){const normal=username.trim().replace(/^@/,'').toLowerCase();if(!/^[a-z][a-z0-9_]{2,29}$/.test(normal)){setNote('Use 3–30 lowercase letters, numbers or underscores, starting with a letter.');return;}setBusy(true);const values={username:normal,display_name:name.trim()||normal};const db=createClient();const r=exists?await db.from('user_handles').update(values).eq('user_id',userId):await db.from('user_handles').insert({...values,user_id:userId});setBusy(false);setNote(r.error?r.error.code==='23505'?'That username is taken.':r.error.code==='22023'?'Username changes are limited to once every seven days; reserved names are unavailable.':'Could not save your username.':'Username saved.');if(!r.error){setExists(true);setUsername(normal);}}
 async function account(action:'link'|'login'|'password'|'logout'){setBusy(true);setNote('');try{const db=createClient();const r=action==='link'?await db.auth.updateUser({email},{emailRedirectTo:getSiteOrigin()+'/auth/callback'}):action==='login'?await db.auth.signInWithPassword({email,password}):action==='password'?await db.auth.updateUser({password}):await db.auth.signOut();if(r.error){setNote(action==='login'?'Sign-in failed. Check your email and password.':'Account update failed. Verify your email first, or retry shortly.');}else if(action==='link')setNote('Check your email to verify this account. Then return here to set a password.');else if(action==='password')setNote('Password saved. You can now sign in on another device.');else{router.push('/build');router.refresh();}}catch{setNote('Account service could not be reached.');}finally{setBusy(false);}}
 return <div className="space-y-3"><label className="block text-sm">Username<input className="platform-input mt-1 w-full" value={username} onChange={e=>setUsername(e.target.value)} placeholder="@yourname" maxLength={31}/></label><label className="block text-sm">Display name<input className="platform-input mt-1 w-full" value={name} onChange={e=>setName(e.target.value)} maxLength={80}/></label><button className="platform-button" disabled={busy} onClick={()=>void save()}>Save username</button><hr className="my-5"/><p className="text-sm">{anonymous?'Link your guest workspace to an email to keep access across devices.':'Your account is saved. Sign in with your username and password on another device.'}</p>{anonymous&&<label className="block text-sm">Email<input type="email" className="platform-input mt-1 w-full" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>}{anonymous&&<button className="platform-button" disabled={busy||!email.includes('@')} onClick={()=>void account('link')}>Link this workspace to email</button>}<label className="block text-sm">Password<input type="password" autoComplete={anonymous?'current-password':'new-password'} className="platform-input mt-1 w-full" minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="flex flex-wrap gap-2">{anonymous?<button className="platform-button" disabled={busy||!email||password.length<8} onClick={()=>{if(window.confirm('Sign in to an existing account? This guest workspace will remain separate. Link its email first if you need to keep access.'))void account('login');}}>Sign in to existing account</button>:<><button className="platform-button" disabled={busy||password.length<8} onClick={()=>void account('password')}>Set password</button><button className="platform-button" disabled={busy} onClick={()=>void account('logout')}>Sign out</button></>}</div><p className="text-sm" role="status">{note}</p></div>;
}
