'use client';
import {useState} from 'react';
import {Dialog} from 'radix-ui';
import {createClient} from '@/lib/supabase/client';
import {useShell} from '@/components/shell/shell-context';
import type {HandleRow,ProjectSnapshot} from '@/lib/projects/types';
export function PeoplePanel({project}:{project:ProjectSnapshot}){
 const {user}=useShell();const [people,setPeople]=useState<(Partial<HandleRow>&{user_id:string;role:string})[]>([]);const [matches,setMatches]=useState<HandleRow[]>([]);const [query,setQuery]=useState('');const [role,setRole]=useState<'editor'|'viewer'>('editor');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);
 async function load(){const db=createClient();const r=await db.from('project_members').select('user_id,role').eq('project_id',project.id);if(r.error){setNote('Could not load people.');return;}const all=[{user_id:project.owner_id,role:'owner'},...(r.data??[])];const names=await db.from('user_handles').select('*').in('user_id',all.map(p=>p.user_id));setPeople(all.map(p=>({...names.data?.find(n=>n.user_id===p.user_id),...p})));}
 async function search(){const q=query.replace(/^@/,'').trim().toLowerCase();if(!/^[a-z][a-z0-9_]{1,29}$/.test(q)){setNote('Enter at least two username characters.');return;}setBusy(true);const r=await createClient().from('user_handles').select('*').ilike('username',q.replaceAll('_','\\_')+'%').neq('user_id',user.id).limit(8);setBusy(false);if(r.error)setNote('Search is unavailable.');else{setNote('');setMatches(r.data??[]);}}
 async function invite(h:HandleRow){setBusy(true);const r=await createClient().from('project_invites').insert({project_id:project.id,inviter_id:user.id,invitee_id:h.user_id,role});setBusy(false);setNote(r.error?r.error.code==='23505'?'An invitation is already pending.':'Could not invite this user.':`Invitation sent to @${h.username}.`);}
 async function change(id:string,value:string){setBusy(true);const db=createClient();const r=value==='remove'?await db.from('project_members').delete().eq('project_id',project.id).eq('user_id',id):await db.from('project_members').update({role:value as 'editor'|'viewer'}).eq('project_id',project.id).eq('user_id',id);setBusy(false);if(r.error)setNote('Could not update permissions.');else await load();}
 return <Dialog.Root onOpenChange={open=>{if(open)void load();}}><Dialog.Trigger className="platform-button">People</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm"/><Dialog.Content className="platform-card fixed left-1/2 top-1/2 z-50 max-h-[85dvh] w-[min(92vw,480px)] -translate-x-1/2 -translate-y-1/2 overflow-auto"><Dialog.Title className="text-xl">Project people</Dialog.Title><Dialog.Description className="my-3 text-sm text-muted-foreground">Editors can build. Viewers can read the project and preview.</Dialog.Description>{people.map(p=><div className="flex items-center justify-between gap-2 border-b py-3" key={p.user_id}><span>{p.username?'@'+p.username:'User without a username'}</span>{project.role==='owner'&&p.role!=='owner'?<select aria-label={`Role for ${p.username??'collaborator'}`} className="platform-input" disabled={busy} value={p.role} onChange={e=>void change(p.user_id,e.target.value)}><option value="editor">Editor</option><option value="viewer">Viewer</option><option value="remove">Remove</option></select>:<span className="text-xs text-subtle">{p.role}</span>}</div>)}{project.role==='owner'&&<form className="mt-5 space-y-3" onSubmit={e=>{e.preventDefault();void search();}}><label className="block text-sm">Add collaborator by username<input className="platform-input mt-2 w-full" value={query} placeholder="@username" onChange={e=>setQuery(e.target.value)}/></label><div className="flex gap-2"><select aria-label="Invitation role" className="platform-input" value={role} onChange={e=>setRole(e.target.value as 'editor'|'viewer')}><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button className="platform-button" disabled={busy}>Search usernames</button></div>{matches.map(h=><div key={h.user_id} className="flex justify-between py-2"><span>@{h.username}</span><button type="button" className="platform-button" disabled={busy} onClick={()=>void invite(h)}>Invite</button></div>)}</form>}<p role="status" className="my-3 text-sm">{note}</p><Dialog.Close className="platform-button">Close</Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
